site_name: Computer Science Literacy Course
site_author: Andrea Diamantini
copyright: Andrea Diamantini (c) 2022

# ----------------------------------------------------

theme:
  name: material
  palette:
    primary: pink
    accent: amber
  font:
    text: Roboto
    code: Roboto Mono
  language: it
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
    - content.code.copy
  plugins:
    - search:
        lang: it

extra_css:
- stylesheets/extra.css

# ----------------------------------------------------

markdown_extensions:
  - admonition: {}
  - attr_list: {}
  - toc: {}
  - def_list: {}
  - pymdownx.emoji: {}
  - pymdownx.tasklist: {custom_checkbox: True}
  - pymdownx.highlight: {anchor_linenums: True}
  - pymdownx.inlinehilite: {}
  - pymdownx.snippets: {}
  - pymdownx.superfences: {}


# -----------------------------------------------------------------------------------------------
 
nav:
  - Home: index.md
  - Basics:
    - Introduzione: basics/00_intro.md
  - Hardware & Software:
    - Introduzione: hwsw/00_intro.md
  - Libreoffice:
    - Introduzione: libreoffice/00_intro.md
  - Web:
    - Introduzione: web/00_intro.md
  - About: about.md

